<center><img src=https://lh3.googleusercontent.com/d/1EmH3Jks5CpJy0zK3JbkvJZkeqWtVcxhB width=600></center>

# Math with Python

Let's use Python to solve some math questions.

## Exercise 1

Create a null vector of size 10. (Hint: use numpy)

In [2]:
import numpy as np

null = np.zeros(10)

print(null)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


## Exercise 2

Create a null vector of size 10 and set the fifth value to be 1.

In [3]:
import numpy as np

null = np.zeros(10)
null[4] = 1

print(null)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


## Exercise 3

Create a 8x8 matrix and fill it with a checkerboard pattern (1 and 0 in alternating order).

In [4]:
matrix = np.zeros((8,8))
matrix[0::2, 0::2] = 1
matrix[1::2 , 1::2] =1
print(matrix)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


## Exercise 4

Create a $5x5$ random matrix and normalize each column.

In [5]:
import numpy as np

data = np.random.rand(5 , 5) * 100
print(data)
col_totals = data.sum(axis=0)
res = data / col_totals
print(res)
print(res.sum(axis=0))


[[64.34342554 41.40819993 43.1190867   6.87327703 49.85310981]
 [47.03578974 55.22217021 13.6586395  65.78554154 77.53317544]
 [53.16795251 45.54411208  3.33189668 95.55746661 63.87853725]
 [26.59497178 68.83124291 51.75571168 37.87385595 90.89382718]
 [62.66366902 19.36560235 54.27530619 28.55009923 45.64546654]]
[[0.25351439 0.17974546 0.25953365 0.02929283 0.15208201]
 [0.18532196 0.23970939 0.08221131 0.28036769 0.23652289]
 [0.2094828  0.1976987  0.02005468 0.40725097 0.19486801]
 [0.10478472 0.2987839  0.31151747 0.16141245 0.27728092]
 [0.24689612 0.08406255 0.3266829  0.12167606 0.13924617]]
[1. 1. 1. 1. 1.]


## Exercise 5

Multiply a $5x3$ matrix by a $3x2$ matrix (dot product).

In [6]:
import numpy as np

A = np.random.randint(1, 10, (5, 3))
B = np.random.randint(1, 10, (3, 2))

result = np.dot(A, B)
print(result)

[[ 39  79]
 [126 154]
 [ 81  91]
 [123 128]
 [ 90 133]]


## Exercise 6

Find out if the vector represented by $(−16, 3, 5)$  is orthogonal to $a = (1, −3, 5)$ and $b = (2, −1, 7)$.




In [7]:
import numpy as np

prim = np.array([-16, 3, 5])
a = np.array([1, -3, 5])
b = np.array([2, -1, 7])

print(np.dot(prim, a))
print(np.dot(prim, b))

0
0


## Exercise 7

Create the matrix $$\begin{bmatrix} 1 & 5 & 2 \\ 2 & 3 & -1 \\ 0 & 1 & -5 \end{bmatrix}$$

and compute its determinant and inverse. (use numpy function)

In [8]:
import numpy as np

A = np.array([
    [1, 5, 2],
    [2, 3, -1],
    [0, 1, -5]
])
det_A = np.linalg.det(A)
inv_A = np.linalg.det(A)

print(A)
print(det_A)
print(inv_A)



[[ 1  5  2]
 [ 2  3 -1]
 [ 0  1 -5]]
40.000000000000014
40.000000000000014


## Exercise 8

Given the two equations below, solve for $x_{1}$ and $x_{2}$ 

$x_{1} + 3x_{2} = 2$

$x_{1} + 2x_{2} = 0$

(Hint: Remember $AX = B$, use the linalg function from numpy)




In [9]:
import numpy as np

A = np.array([[1, 3], 
              [1, 2]])

B = np.array([2, 0])

X = np.linalg.solve(A, B)

print("x1 =", X[0])
print("x2 =", X[1])

x1 = -4.0
x2 = 2.0


## Exercise 9

Find the critical points of the function $f(x)= x^3−2x^2+x$ and use the second derivative test to find the maximum on interval $x⊂[0,1]$. 

**Hint 1**: remember the concepts of first differentiation and second differentiation;

**Hint 2**: `sympy` python library with use of `solve`, `diff`.

In [10]:
import sympy as sp

x = sp.Symbol('x')

f = x**3 - 2*x**2 + x

f_prime = sp.diff(f, x)

critical_points = sp.solve(f_prime, x)

print(f"Critical Points: {critical_points}")

f_double_prime = sp.diff(f_prime, x)

for point in critical_points:
    if 0 <= point <= 1:
        test_value = f_double_prime.subs(x, point)
        if test_value < 0:
            print(f"Point {point} is a Maximum (double prime = {test_value})")
        elif test_value > 0:
            print(f"Point {point} is a Minimum (double prime = {test_value})")

Critical Points: [1/3, 1]
Point 1/3 is a Maximum (double prime = -2)
Point 1 is a Minimum (double prime = 2)


## Exercise 10

Maximise $f(x, y, z) = xy + yz$, subject to the constraints $x + 2y = 6$ and $x − 3z = 0$. 

**Hint 1**: set up the Lagrange equation, $f (x, y, z) − λ(constraint1) − μ(constraint2)$; 

**Hint 2**: Set partial derivatives to zero and solve the following set of equations; 

**Hint 3**: Use `solve`. 

In [11]:
import sympy as sp

x, y, z, lam, mu = sp.symbols('x y z lam mu')

f = x*y + y*z
g1 = x + 2*y - 6
g2 = x - 3*z

L = f - lam * g1 - mu * g2

eqs = [
    sp.diff(L, x),
    sp.diff(L, y),
    sp.diff(L, z),
    sp.diff(L, lam),
    sp.diff(L, mu)
]

solution = sp.solve(eqs, (x, y, z, lam, mu))

print(solution)

{lam: 2, mu: -1/2, x: 3, y: 3/2, z: 1}
